apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Chart.Name }}-secrets
  namespace: {{ .Values.mysql.namespace.name }}
type: Opaque
data:
{{- range $k, $v:= .Values.mysql.secrets }}
  {{ $k }}: {{ $v }}
{{- end }}
