todoapp:
  namespace:
    name: todoapp

  secrets:
    SECRET_KEY: QGUyKHl4KXYmdGdoM19zPTB5amEtaSFkcGVieHN6XmRnNDd4KS1rJmtxXzN6Zio5ZSoK
    DB_NAME: "YXBwX2RiCg=="
    DB_USER: "YXBwX3VzZXI="
    DB_PASSWORD: "MTIzNA=="
    DB_HOST: "bXlzcWwtMC5teXNxbC5teXNxbC5zdmMuY2x1c3Rlci5sb2NhbAo="

  resources:
    requests:
      memory: "256Mi"
      cpu: "150m"
    limits:
      memory: "256Mi"
      cpu: "150m"

  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

  containers:
    repository: ikulyk404/todoapp
    version: 4.0.1

  affinity:
    key: app
    values:
    - todoapp

  hpa:
    minReplicas: 2
    maxReplicas: 5
    cpu:
      averageUtilization: 70
    memory:
      averageUtilization: 70

  pv:
    capacity:
      storage: 1Gi

  pvc:
    requests:
      storage: 1Gi

  serviceAccount:
    name: secrets-reader