
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data
  namespace: {{ .Values.todoapp.namespace.name }}
spec:
  volumeName: pv-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.todoapp.pvc.requests.storage }}
